version: '3'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3100:3100"
  product-service:
    build:
      context: ./product-service
    ports:
      - "3200:3200"
